### PR TITLE
Restyle blog

### PR DESCRIPTION
**Pull request by Kenadia**
Before
screen shot 2015-08-28 at 3 51 49 pm

After
screen shot 2015-08-28 at 3 51 42 pm

Fancy nav links
screen shot 2015-08-28 at 3 52 23 pm

### CODE REVIEW

**Comment by cobalthex** [comment]
One nit, change the color of 'Join us'

**Comment by diwu1989** [comment]
yep, was just gonna say the same thing, i think it should be way lighter

**Comment by cmds4410** [comment]
The mixture of light and dark text on the same color background is pretty jarring! Especially when in the same paragraph.

**Comment by Kenadia** [comment]
2% better, 1% worse

**Comment by cmds4410** [comment]
@Kenadia Not true, it was like that before your PR! So just 2% better :)

**Pull request merged**
